### ISSUE TITLE
Public repo

### ISSUE THREAD

**Issue by mgroesink** [kevinveld2001/adventofcode-2021#1]
Niet zo leuk om een public repo te gebruiken voor Advent Of Code. Kun je deze veranderen naar een private repo?

**Comment by kevinveld2001** [comment]
Ik hou hem liver openbaar. De andwoorden staan toch al overal op interenet. En het is tog bedoeld voor de fun dus van een ander afkijken is gewoon niet leuk en moeten ze dus niet doen.
